set(_AMENT_PACKAGE_NAME "image_tools_custom")
set(image_tools_custom_VERSION "0.7.9")
set(image_tools_custom_MAINTAINER "Johnny Liu <johnny@clearbot.org>")
set(image_tools_custom_BUILD_DEPENDS "rclcpp" "sensor_msgs" "std_msgs")
set(image_tools_custom_BUILDTOOL_DEPENDS "ament_cmake")
set(image_tools_custom_BUILD_EXPORT_DEPENDS )
set(image_tools_custom_BUILDTOOL_EXPORT_DEPENDS )
set(image_tools_custom_EXEC_DEPENDS "rclcpp" "sensor_msgs" "std_msgs")
set(image_tools_custom_TEST_DEPENDS "ament_cmake_pytest" "ament_lint_auto" "ament_lint_common" "launch" "launch_testing" "launch_testing_ament_cmake" "launch_testing_ros" "rmw_implementation_cmake")
set(image_tools_custom_GROUP_DEPENDS )
set(image_tools_custom_MEMBER_OF_GROUPS )
set(image_tools_custom_DEPRECATED "")
set(image_tools_custom_EXPORT_TAGS)
list(APPEND image_tools_custom_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
